services:
  laravel-docker:
    container_name: portal
    build: .
    volumes: 
      - ./laravel-app:/var/www/html
    ports:
      - 9004:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portal
    ports:
    - 3308:3306


  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9005:80
    environment:
      - PMA_ARBITRARY=1